/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutophagyScore {
  'sleepScore' : bigint,
  'stressScore' : bigint,
  'totalScore' : bigint,
  'fastingScore' : bigint,
  'trainingScore' : bigint,
}
export type BMIIndicatorCategory = { 'slightlyLow' : null } |
  { 'tooHigh' : null } |
  { 'tooLow' : null } |
  { 'slightlyHigh' : null } |
  { 'optimal' : null };
export interface BodyCompentry {
  'weight' : number,
  'muscleMass' : number,
  'timestamp' : Time,
  'bodyFatPercentage' : number,
}
export interface BodyComposition {
  'bmi' : number,
  'currentBodyFatPercentage' : number,
  'bmiCategory' : BMIIndicatorCategory,
  'history' : Array<BodyCompentry>,
  'currentMuscleMass' : number,
  'currentWeight' : number,
}
export interface BodyCompositionInput {
  'weight' : number,
  'muscleMass' : number,
  'bodyFatPercentage' : number,
}
export type ColorIndicator = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface DayData {
  'completionTime' : Time,
  'longevityScore' : LongevityScore,
  'routines' : DayRoutines,
  'autophagyScore' : AutophagyScore,
}
export interface DayRoutines {
  'nutritionMetrics' : NutritionMetrics,
  'bodyComposition' : BodyCompositionInput,
  'stressMetrics' : StressMetrics,
  'fastingSession' : FastingSession,
  'sleepMetrics' : SleepMetrics,
  'trainingSessions' : Array<Training>,
}
export interface FastingSession {
  'isCompleted' : boolean,
  'durationHours' : bigint,
  'endTimestamp' : Time,
  'startTimestamp' : Time,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface JournalEntry {
  'id' : bigint,
  'content' : string,
  'timestamp' : Time,
}
export interface LegalDisclaimerStatus {
  'lastSeenTimestamp' : [] | [Time],
  'hasSeenDisclaimer' : boolean,
}
export interface LongevityScore {
  'autophagyCouplingScore' : bigint,
  'totalScore' : bigint,
  'nutritionScore' : bigint,
  'bodyCompositionScore' : bigint,
}
export interface NutritionMetrics {
  'veggieIntake' : bigint,
  'proteinTarget' : bigint,
  'proteinIntake' : bigint,
  'waterIntake' : bigint,
}
export interface Preferences { 'language' : { 'de' : null } | { 'en' : null } }
export interface QueryTokenTransaction {
  'description' : string,
  'timestamp' : Time,
  'tokenType' : TokenType,
  'amount' : bigint,
  'transactionId' : bigint,
}
export interface ResetResponse {
  'supplements' : Array<SupplementEntry>,
  'message' : string,
}
export type RoutineDayId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SleepMetrics {
  'durationHours' : bigint,
  'qualityRating' : bigint,
}
export interface SortResponse {
  'supplements' : Array<SupplementEntry>,
  'message' : string,
}
export interface StressMetrics {
  'stressColorIndicator' : ColorIndicator,
  'bloodPressureDiastolic' : bigint,
  'pulse' : bigint,
  'bloodPressureSystolic' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupplementEntry {
  'id' : bigint,
  'dosage' : string,
  'name' : string,
  'note' : [] | [string],
  'time' : string,
  'completed' : boolean,
}
export interface SupplementResponse {
  'supplements' : Array<SupplementEntry>,
  'message' : string,
}
export type Time = bigint;
export type TokenBalance = bigint;
export interface TokenDistribution {
  'communityRewardPool' : TokenBalance,
  'creatorTreasury' : TokenBalance,
  'totalSupply' : TokenBalance,
}
export interface TokenSupply {
  'circulatingSupply' : TokenBalance,
  'supplyCap' : TokenBalance,
  'totalSupply' : TokenBalance,
  'remainingSupply' : TokenBalance,
}
export type TokenType = { 'goal' : null } |
  { 'routine' : null } |
  { 'bonus' : null };
export interface Training {
  'durationMins' : bigint,
  'trainingType' : TrainingType,
  'intensity' : TrainingIntensity,
}
export type TrainingIntensity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TrainingType = { 'other' : string } |
  { 'yoga' : null } |
  { 'strength' : null } |
  { 'cardio' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'birthYear' : bigint,
  'name' : string,
  'preferences' : Preferences,
  'gender' : Gender,
  'bodyHeightCm' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UtilityType = { 'advancedAnalytics' : null } |
  { 'longevityCircleMembership' : null } |
  { 'supplementPlans' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addSupplement' : ActorMethod<
    [string, string, string, [] | [string], boolean],
    SupplementResponse
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupInactiveAccounts' : ActorMethod<[], undefined>,
  'clearTrainings' : ActorMethod<[], undefined>,
  'completeRoutines' : ActorMethod<[DayRoutines], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createJournalEntry' : ActorMethod<[string], JournalEntry>,
  'deleteJournalEntry' : ActorMethod<[bigint], undefined>,
  'deleteSupplement' : ActorMethod<[bigint], undefined>,
  'getAllDailyRoutines' : ActorMethod<
    [],
    [Array<[RoutineDayId, DayData]>, bigint]
  >,
  'getAllSupplements' : ActorMethod<[], Array<SupplementEntry>>,
  'getAutophagyScore' : ActorMethod<[bigint], [] | [AutophagyScore]>,
  'getBalance' : ActorMethod<[Principal], TokenBalance>,
  'getBodyComposition' : ActorMethod<[], [] | [BodyComposition]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyRoutineStats' : ActorMethod<[], bigint>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getLegalDisclaimerStatus' : ActorMethod<[], LegalDisclaimerStatus>,
  'getLegalDisclaimerStatusFor' : ActorMethod<
    [Principal],
    LegalDisclaimerStatus
  >,
  'getLongevityScore' : ActorMethod<[bigint], [] | [LongevityScore]>,
  'getPoolBalances' : ActorMethod<[], TokenDistribution>,
  'getPreferences' : ActorMethod<[], Preferences>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupplementStoreSize' : ActorMethod<[], bigint>,
  'getTokenBalance' : ActorMethod<[], bigint>,
  'getTokenSupplyInfo' : ActorMethod<[], TokenSupply>,
  'getTokenTransactions' : ActorMethod<[], Array<QueryTokenTransaction>>,
  'getTrainings' : ActorMethod<[], Array<Training>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'mintRewardTokens' : ActorMethod<[Principal, TokenBalance], undefined>,
  'resetAllSupplements' : ActorMethod<[], ResetResponse>,
  'resetAnalyses' : ActorMethod<[], undefined>,
  'resetLegalDisclaimerStatus' : ActorMethod<[], undefined>,
  'resetTokenDistribution' : ActorMethod<[], TokenDistribution>,
  'saveBodyComposition' : ActorMethod<[number, number, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTraining' : ActorMethod<[Training], undefined>,
  'setLegalDisclaimerSeen' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'sortSupplementsByTime' : ActorMethod<[], SortResponse>,
  'toggleSupplement' : ActorMethod<[bigint], undefined>,
  'transferTokens' : ActorMethod<[Principal, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlockUtility' : ActorMethod<[UtilityType], undefined>,
  'updateJournalEntry' : ActorMethod<[bigint, string], undefined>,
  'updateSupplement' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];