/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SupplementEntry = IDL.Record({
  'id' : IDL.Nat,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'time' : IDL.Text,
  'completed' : IDL.Bool,
});
export const SupplementResponse = IDL.Record({
  'supplements' : IDL.Vec(SupplementEntry),
  'message' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NutritionMetrics = IDL.Record({
  'veggieIntake' : IDL.Nat,
  'proteinTarget' : IDL.Nat,
  'proteinIntake' : IDL.Nat,
  'waterIntake' : IDL.Nat,
});
export const BodyCompositionInput = IDL.Record({
  'weight' : IDL.Float64,
  'muscleMass' : IDL.Float64,
  'bodyFatPercentage' : IDL.Float64,
});
export const ColorIndicator = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const StressMetrics = IDL.Record({
  'stressColorIndicator' : ColorIndicator,
  'bloodPressureDiastolic' : IDL.Nat,
  'pulse' : IDL.Nat,
  'bloodPressureSystolic' : IDL.Nat,
});
export const Time = IDL.Int;
export const FastingSession = IDL.Record({
  'isCompleted' : IDL.Bool,
  'durationHours' : IDL.Nat,
  'endTimestamp' : Time,
  'startTimestamp' : Time,
});
export const SleepMetrics = IDL.Record({
  'durationHours' : IDL.Nat,
  'qualityRating' : IDL.Nat,
});
export const TrainingType = IDL.Variant({
  'other' : IDL.Text,
  'yoga' : IDL.Null,
  'strength' : IDL.Null,
  'cardio' : IDL.Null,
});
export const TrainingIntensity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Training = IDL.Record({
  'durationMins' : IDL.Nat,
  'trainingType' : TrainingType,
  'intensity' : TrainingIntensity,
});
export const DayRoutines = IDL.Record({
  'nutritionMetrics' : NutritionMetrics,
  'bodyComposition' : BodyCompositionInput,
  'stressMetrics' : StressMetrics,
  'fastingSession' : FastingSession,
  'sleepMetrics' : SleepMetrics,
  'trainingSessions' : IDL.Vec(Training),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const RoutineDayId = IDL.Nat;
export const LongevityScore = IDL.Record({
  'autophagyCouplingScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'nutritionScore' : IDL.Nat,
  'bodyCompositionScore' : IDL.Nat,
});
export const AutophagyScore = IDL.Record({
  'sleepScore' : IDL.Nat,
  'stressScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'fastingScore' : IDL.Nat,
  'trainingScore' : IDL.Nat,
});
export const DayData = IDL.Record({
  'completionTime' : Time,
  'longevityScore' : LongevityScore,
  'routines' : DayRoutines,
  'autophagyScore' : AutophagyScore,
});
export const TokenBalance = IDL.Nat;
export const BMIIndicatorCategory = IDL.Variant({
  'slightlyLow' : IDL.Null,
  'tooHigh' : IDL.Null,
  'tooLow' : IDL.Null,
  'slightlyHigh' : IDL.Null,
  'optimal' : IDL.Null,
});
export const BodyCompentry = IDL.Record({
  'weight' : IDL.Float64,
  'muscleMass' : IDL.Float64,
  'timestamp' : Time,
  'bodyFatPercentage' : IDL.Float64,
});
export const BodyComposition = IDL.Record({
  'bmi' : IDL.Float64,
  'currentBodyFatPercentage' : IDL.Float64,
  'bmiCategory' : BMIIndicatorCategory,
  'history' : IDL.Vec(BodyCompentry),
  'currentMuscleMass' : IDL.Float64,
  'currentWeight' : IDL.Float64,
});
export const Preferences = IDL.Record({
  'language' : IDL.Variant({ 'de' : IDL.Null, 'en' : IDL.Null }),
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'birthYear' : IDL.Nat,
  'name' : IDL.Text,
  'preferences' : Preferences,
  'gender' : Gender,
  'bodyHeightCm' : IDL.Nat,
});
export const LegalDisclaimerStatus = IDL.Record({
  'lastSeenTimestamp' : IDL.Opt(Time),
  'hasSeenDisclaimer' : IDL.Bool,
});
export const TokenDistribution = IDL.Record({
  'communityRewardPool' : TokenBalance,
  'creatorTreasury' : TokenBalance,
  'totalSupply' : TokenBalance,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TokenSupply = IDL.Record({
  'circulatingSupply' : TokenBalance,
  'supplyCap' : TokenBalance,
  'totalSupply' : TokenBalance,
  'remainingSupply' : TokenBalance,
});
export const TokenType = IDL.Variant({
  'goal' : IDL.Null,
  'routine' : IDL.Null,
  'bonus' : IDL.Null,
});
export const QueryTokenTransaction = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
  'tokenType' : TokenType,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Nat,
});
export const ResetResponse = IDL.Record({
  'supplements' : IDL.Vec(SupplementEntry),
  'message' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const SortResponse = IDL.Record({
  'supplements' : IDL.Vec(SupplementEntry),
  'message' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UtilityType = IDL.Variant({
  'advancedAnalytics' : IDL.Null,
  'longevityCircleMembership' : IDL.Null,
  'supplementPlans' : IDL.Null,
});

export const idlService = IDL.Service({
  'addSupplement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [SupplementResponse],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupInactiveAccounts' : IDL.Func([], [], []),
  'clearTrainings' : IDL.Func([], [], []),
  'completeRoutines' : IDL.Func([DayRoutines], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createJournalEntry' : IDL.Func([IDL.Text], [JournalEntry], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteSupplement' : IDL.Func([IDL.Nat], [], []),
  'getAllDailyRoutines' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(RoutineDayId, DayData)), IDL.Int],
      ['query'],
    ),
  'getAllSupplements' : IDL.Func([], [IDL.Vec(SupplementEntry)], ['query']),
  'getAutophagyScore' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AutophagyScore)],
      ['query'],
    ),
  'getBalance' : IDL.Func([IDL.Principal], [TokenBalance], ['query']),
  'getBodyComposition' : IDL.Func([], [IDL.Opt(BodyComposition)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyRoutineStats' : IDL.Func([], [IDL.Nat], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getLegalDisclaimerStatus' : IDL.Func([], [LegalDisclaimerStatus], ['query']),
  'getLegalDisclaimerStatusFor' : IDL.Func(
      [IDL.Principal],
      [LegalDisclaimerStatus],
      ['query'],
    ),
  'getLongevityScore' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(LongevityScore)],
      ['query'],
    ),
  'getPoolBalances' : IDL.Func([], [TokenDistribution], ['query']),
  'getPreferences' : IDL.Func([], [Preferences], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupplementStoreSize' : IDL.Func([], [IDL.Nat], ['query']),
  'getTokenBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getTokenSupplyInfo' : IDL.Func([], [TokenSupply], ['query']),
  'getTokenTransactions' : IDL.Func(
      [],
      [IDL.Vec(QueryTokenTransaction)],
      ['query'],
    ),
  'getTrainings' : IDL.Func([], [IDL.Vec(Training)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'mintRewardTokens' : IDL.Func([IDL.Principal, TokenBalance], [], []),
  'resetAllSupplements' : IDL.Func([], [ResetResponse], []),
  'resetAnalyses' : IDL.Func([], [], []),
  'resetLegalDisclaimerStatus' : IDL.Func([], [], []),
  'resetTokenDistribution' : IDL.Func([], [TokenDistribution], []),
  'saveBodyComposition' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTraining' : IDL.Func([Training], [], []),
  'setLegalDisclaimerSeen' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'sortSupplementsByTime' : IDL.Func([], [SortResponse], []),
  'toggleSupplement' : IDL.Func([IDL.Nat], [], []),
  'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlockUtility' : IDL.Func([UtilityType], [], []),
  'updateJournalEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateSupplement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SupplementEntry = IDL.Record({
    'id' : IDL.Nat,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'time' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const SupplementResponse = IDL.Record({
    'supplements' : IDL.Vec(SupplementEntry),
    'message' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NutritionMetrics = IDL.Record({
    'veggieIntake' : IDL.Nat,
    'proteinTarget' : IDL.Nat,
    'proteinIntake' : IDL.Nat,
    'waterIntake' : IDL.Nat,
  });
  const BodyCompositionInput = IDL.Record({
    'weight' : IDL.Float64,
    'muscleMass' : IDL.Float64,
    'bodyFatPercentage' : IDL.Float64,
  });
  const ColorIndicator = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const StressMetrics = IDL.Record({
    'stressColorIndicator' : ColorIndicator,
    'bloodPressureDiastolic' : IDL.Nat,
    'pulse' : IDL.Nat,
    'bloodPressureSystolic' : IDL.Nat,
  });
  const Time = IDL.Int;
  const FastingSession = IDL.Record({
    'isCompleted' : IDL.Bool,
    'durationHours' : IDL.Nat,
    'endTimestamp' : Time,
    'startTimestamp' : Time,
  });
  const SleepMetrics = IDL.Record({
    'durationHours' : IDL.Nat,
    'qualityRating' : IDL.Nat,
  });
  const TrainingType = IDL.Variant({
    'other' : IDL.Text,
    'yoga' : IDL.Null,
    'strength' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const TrainingIntensity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Training = IDL.Record({
    'durationMins' : IDL.Nat,
    'trainingType' : TrainingType,
    'intensity' : TrainingIntensity,
  });
  const DayRoutines = IDL.Record({
    'nutritionMetrics' : NutritionMetrics,
    'bodyComposition' : BodyCompositionInput,
    'stressMetrics' : StressMetrics,
    'fastingSession' : FastingSession,
    'sleepMetrics' : SleepMetrics,
    'trainingSessions' : IDL.Vec(Training),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const RoutineDayId = IDL.Nat;
  const LongevityScore = IDL.Record({
    'autophagyCouplingScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'nutritionScore' : IDL.Nat,
    'bodyCompositionScore' : IDL.Nat,
  });
  const AutophagyScore = IDL.Record({
    'sleepScore' : IDL.Nat,
    'stressScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'fastingScore' : IDL.Nat,
    'trainingScore' : IDL.Nat,
  });
  const DayData = IDL.Record({
    'completionTime' : Time,
    'longevityScore' : LongevityScore,
    'routines' : DayRoutines,
    'autophagyScore' : AutophagyScore,
  });
  const TokenBalance = IDL.Nat;
  const BMIIndicatorCategory = IDL.Variant({
    'slightlyLow' : IDL.Null,
    'tooHigh' : IDL.Null,
    'tooLow' : IDL.Null,
    'slightlyHigh' : IDL.Null,
    'optimal' : IDL.Null,
  });
  const BodyCompentry = IDL.Record({
    'weight' : IDL.Float64,
    'muscleMass' : IDL.Float64,
    'timestamp' : Time,
    'bodyFatPercentage' : IDL.Float64,
  });
  const BodyComposition = IDL.Record({
    'bmi' : IDL.Float64,
    'currentBodyFatPercentage' : IDL.Float64,
    'bmiCategory' : BMIIndicatorCategory,
    'history' : IDL.Vec(BodyCompentry),
    'currentMuscleMass' : IDL.Float64,
    'currentWeight' : IDL.Float64,
  });
  const Preferences = IDL.Record({
    'language' : IDL.Variant({ 'de' : IDL.Null, 'en' : IDL.Null }),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'birthYear' : IDL.Nat,
    'name' : IDL.Text,
    'preferences' : Preferences,
    'gender' : Gender,
    'bodyHeightCm' : IDL.Nat,
  });
  const LegalDisclaimerStatus = IDL.Record({
    'lastSeenTimestamp' : IDL.Opt(Time),
    'hasSeenDisclaimer' : IDL.Bool,
  });
  const TokenDistribution = IDL.Record({
    'communityRewardPool' : TokenBalance,
    'creatorTreasury' : TokenBalance,
    'totalSupply' : TokenBalance,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TokenSupply = IDL.Record({
    'circulatingSupply' : TokenBalance,
    'supplyCap' : TokenBalance,
    'totalSupply' : TokenBalance,
    'remainingSupply' : TokenBalance,
  });
  const TokenType = IDL.Variant({
    'goal' : IDL.Null,
    'routine' : IDL.Null,
    'bonus' : IDL.Null,
  });
  const QueryTokenTransaction = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
    'tokenType' : TokenType,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Nat,
  });
  const ResetResponse = IDL.Record({
    'supplements' : IDL.Vec(SupplementEntry),
    'message' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const SortResponse = IDL.Record({
    'supplements' : IDL.Vec(SupplementEntry),
    'message' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UtilityType = IDL.Variant({
    'advancedAnalytics' : IDL.Null,
    'longevityCircleMembership' : IDL.Null,
    'supplementPlans' : IDL.Null,
  });
  
  return IDL.Service({
    'addSupplement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [SupplementResponse],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupInactiveAccounts' : IDL.Func([], [], []),
    'clearTrainings' : IDL.Func([], [], []),
    'completeRoutines' : IDL.Func([DayRoutines], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createJournalEntry' : IDL.Func([IDL.Text], [JournalEntry], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteSupplement' : IDL.Func([IDL.Nat], [], []),
    'getAllDailyRoutines' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(RoutineDayId, DayData)), IDL.Int],
        ['query'],
      ),
    'getAllSupplements' : IDL.Func([], [IDL.Vec(SupplementEntry)], ['query']),
    'getAutophagyScore' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AutophagyScore)],
        ['query'],
      ),
    'getBalance' : IDL.Func([IDL.Principal], [TokenBalance], ['query']),
    'getBodyComposition' : IDL.Func([], [IDL.Opt(BodyComposition)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyRoutineStats' : IDL.Func([], [IDL.Nat], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getLegalDisclaimerStatus' : IDL.Func(
        [],
        [LegalDisclaimerStatus],
        ['query'],
      ),
    'getLegalDisclaimerStatusFor' : IDL.Func(
        [IDL.Principal],
        [LegalDisclaimerStatus],
        ['query'],
      ),
    'getLongevityScore' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LongevityScore)],
        ['query'],
      ),
    'getPoolBalances' : IDL.Func([], [TokenDistribution], ['query']),
    'getPreferences' : IDL.Func([], [Preferences], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupplementStoreSize' : IDL.Func([], [IDL.Nat], ['query']),
    'getTokenBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getTokenSupplyInfo' : IDL.Func([], [TokenSupply], ['query']),
    'getTokenTransactions' : IDL.Func(
        [],
        [IDL.Vec(QueryTokenTransaction)],
        ['query'],
      ),
    'getTrainings' : IDL.Func([], [IDL.Vec(Training)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'mintRewardTokens' : IDL.Func([IDL.Principal, TokenBalance], [], []),
    'resetAllSupplements' : IDL.Func([], [ResetResponse], []),
    'resetAnalyses' : IDL.Func([], [], []),
    'resetLegalDisclaimerStatus' : IDL.Func([], [], []),
    'resetTokenDistribution' : IDL.Func([], [TokenDistribution], []),
    'saveBodyComposition' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTraining' : IDL.Func([Training], [], []),
    'setLegalDisclaimerSeen' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'sortSupplementsByTime' : IDL.Func([], [SortResponse], []),
    'toggleSupplement' : IDL.Func([IDL.Nat], [], []),
    'transferTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlockUtility' : IDL.Func([UtilityType], [], []),
    'updateJournalEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateSupplement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };