/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BodyCompositionInput {
    weight: number;
    muscleMass: number;
    bodyFatPercentage: number;
}
export interface FastingSession {
    isCompleted: boolean;
    durationHours: bigint;
    endTimestamp: Time;
    startTimestamp: Time;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface DayRoutines {
    nutritionMetrics: NutritionMetrics;
    bodyComposition: BodyCompositionInput;
    stressMetrics: StressMetrics;
    fastingSession: FastingSession;
    sleepMetrics: SleepMetrics;
    trainingSessions: Array<Training>;
}
export interface BodyComposition {
    bmi: number;
    currentBodyFatPercentage: number;
    bmiCategory: BMIIndicatorCategory;
    history: Array<BodyCompentry>;
    currentMuscleMass: number;
    currentWeight: number;
}
export interface BodyCompentry {
    weight: number;
    muscleMass: number;
    timestamp: Time;
    bodyFatPercentage: number;
}
export interface AutophagyScore {
    sleepScore: bigint;
    stressScore: bigint;
    totalScore: bigint;
    fastingScore: bigint;
    trainingScore: bigint;
}
export interface SupplementResponse {
    supplements: Array<SupplementEntry>;
    message: string;
}
export interface TokenSupply {
    circulatingSupply: TokenBalance;
    supplyCap: TokenBalance;
    totalSupply: TokenBalance;
    remainingSupply: TokenBalance;
}
export interface LegalDisclaimerStatus {
    lastSeenTimestamp?: Time;
    hasSeenDisclaimer: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type RoutineDayId = bigint;
export interface QueryTokenTransaction {
    description: string;
    timestamp: Time;
    tokenType: TokenType;
    amount: bigint;
    transactionId: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface DayData {
    completionTime: Time;
    longevityScore: LongevityScore;
    routines: DayRoutines;
    autophagyScore: AutophagyScore;
}
export interface Preferences {
    language: Variant_de_en;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SortResponse {
    supplements: Array<SupplementEntry>;
    message: string;
}
export interface Training {
    durationMins: bigint;
    trainingType: TrainingType;
    intensity: TrainingIntensity;
}
export interface TokenDistribution {
    communityRewardPool: TokenBalance;
    creatorTreasury: TokenBalance;
    totalSupply: TokenBalance;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface LongevityScore {
    autophagyCouplingScore: bigint;
    totalScore: bigint;
    nutritionScore: bigint;
    bodyCompositionScore: bigint;
}
export interface JournalEntry {
    id: bigint;
    content: string;
    timestamp: Time;
}
export interface SupplementEntry {
    id: bigint;
    dosage: string;
    name: string;
    note?: string;
    time: string;
    completed: boolean;
}
export interface NutritionMetrics {
    veggieIntake: bigint;
    proteinTarget: bigint;
    proteinIntake: bigint;
    waterIntake: bigint;
}
export interface ResetResponse {
    supplements: Array<SupplementEntry>;
    message: string;
}
export interface SleepMetrics {
    durationHours: bigint;
    qualityRating: bigint;
}
export type TrainingType = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "yoga";
    yoga: null;
} | {
    __kind__: "strength";
    strength: null;
} | {
    __kind__: "cardio";
    cardio: null;
};
export interface StressMetrics {
    stressColorIndicator: ColorIndicator;
    bloodPressureDiastolic: bigint;
    pulse: bigint;
    bloodPressureSystolic: bigint;
}
export type TokenBalance = bigint;
export interface UserProfile {
    birthYear: bigint;
    name: string;
    preferences: Preferences;
    gender: Gender;
    bodyHeightCm: bigint;
}
export enum BMIIndicatorCategory {
    slightlyLow = "slightlyLow",
    tooHigh = "tooHigh",
    tooLow = "tooLow",
    slightlyHigh = "slightlyHigh",
    optimal = "optimal"
}
export enum ColorIndicator {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum TokenType {
    goal = "goal",
    routine = "routine",
    bonus = "bonus"
}
export enum TrainingIntensity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UtilityType {
    advancedAnalytics = "advancedAnalytics",
    longevityCircleMembership = "longevityCircleMembership",
    supplementPlans = "supplementPlans"
}
export enum Variant_de_en {
    de = "de",
    en = "en"
}
export interface backendInterface {
    addSupplement(name: string, dosage: string, time: string, note: string | null, completed: boolean): Promise<SupplementResponse>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanupInactiveAccounts(): Promise<void>;
    clearTrainings(): Promise<void>;
    completeRoutines(newRoutines: DayRoutines): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createJournalEntry(content: string): Promise<JournalEntry>;
    deleteJournalEntry(entryId: bigint): Promise<void>;
    deleteSupplement(supplementId: bigint): Promise<void>;
    getAllDailyRoutines(): Promise<[Array<[RoutineDayId, DayData]>, bigint]>;
    getAllSupplements(): Promise<Array<SupplementEntry>>;
    getAutophagyScore(dayId: bigint): Promise<AutophagyScore | null>;
    getBalance(p: Principal): Promise<TokenBalance>;
    getBodyComposition(): Promise<BodyComposition | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyRoutineStats(): Promise<bigint>;
    getJournalEntries(): Promise<Array<JournalEntry>>;
    getLegalDisclaimerStatus(): Promise<LegalDisclaimerStatus>;
    getLegalDisclaimerStatusFor(p: Principal): Promise<LegalDisclaimerStatus>;
    getLongevityScore(dayId: bigint): Promise<LongevityScore | null>;
    getPoolBalances(): Promise<TokenDistribution>;
    getPreferences(): Promise<Preferences>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSupplementStoreSize(): Promise<bigint>;
    getTokenBalance(): Promise<bigint>;
    getTokenSupplyInfo(): Promise<TokenSupply>;
    getTokenTransactions(): Promise<Array<QueryTokenTransaction>>;
    getTrainings(): Promise<Array<Training>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    mintRewardTokens(user: Principal, amount: TokenBalance): Promise<void>;
    resetAllSupplements(): Promise<ResetResponse>;
    resetAnalyses(): Promise<void>;
    resetLegalDisclaimerStatus(): Promise<void>;
    resetTokenDistribution(): Promise<TokenDistribution>;
    saveBodyComposition(weight: number, bodyFatPercentage: number, muscleMass: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveTraining(training: Training): Promise<void>;
    setLegalDisclaimerSeen(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    sortSupplementsByTime(): Promise<SortResponse>;
    toggleSupplement(supplementId: bigint): Promise<void>;
    transferTokens(to: Principal, amount: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unlockUtility(utilityType: UtilityType): Promise<void>;
    updateJournalEntry(entryId: bigint, newContent: string): Promise<void>;
    updateSupplement(supplementId: bigint, name: string, dosage: string, time: string, note: string | null): Promise<void>;
}
import type { AutophagyScore as _AutophagyScore, BMIIndicatorCategory as _BMIIndicatorCategory, BodyCompentry as _BodyCompentry, BodyComposition as _BodyComposition, BodyCompositionInput as _BodyCompositionInput, ColorIndicator as _ColorIndicator, DayData as _DayData, DayRoutines as _DayRoutines, FastingSession as _FastingSession, Gender as _Gender, LegalDisclaimerStatus as _LegalDisclaimerStatus, LongevityScore as _LongevityScore, NutritionMetrics as _NutritionMetrics, Preferences as _Preferences, QueryTokenTransaction as _QueryTokenTransaction, ResetResponse as _ResetResponse, RoutineDayId as _RoutineDayId, SleepMetrics as _SleepMetrics, SortResponse as _SortResponse, StressMetrics as _StressMetrics, StripeSessionStatus as _StripeSessionStatus, SupplementEntry as _SupplementEntry, SupplementResponse as _SupplementResponse, Time as _Time, TokenType as _TokenType, Training as _Training, TrainingIntensity as _TrainingIntensity, TrainingType as _TrainingType, UserProfile as _UserProfile, UserRole as _UserRole, UtilityType as _UtilityType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSupplement(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: boolean): Promise<SupplementResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplement(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_SupplementResponse_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplement(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_SupplementResponse_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cleanupInactiveAccounts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupInactiveAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupInactiveAccounts();
            return result;
        }
    }
    async clearTrainings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTrainings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTrainings();
            return result;
        }
    }
    async completeRoutines(arg0: DayRoutines): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRoutines(to_candid_DayRoutines_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRoutines(to_candid_DayRoutines_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createJournalEntry(arg0: string): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(arg0);
            return result;
        }
    }
    async deleteJournalEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteSupplement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplement(arg0);
            return result;
        }
    }
    async getAllDailyRoutines(): Promise<[Array<[RoutineDayId, DayData]>, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyRoutines();
                return [
                    from_candid_vec_n23(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyRoutines();
            return [
                from_candid_vec_n23(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async getAllSupplements(): Promise<Array<SupplementEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupplements();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupplements();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAutophagyScore(arg0: bigint): Promise<AutophagyScore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAutophagyScore(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAutophagyScore(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(arg0: Principal): Promise<TokenBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return result;
        }
    }
    async getBodyComposition(): Promise<BodyComposition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBodyComposition();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBodyComposition();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRoutineStats(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRoutineStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRoutineStats();
            return result;
        }
    }
    async getJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries();
            return result;
        }
    }
    async getLegalDisclaimerStatus(): Promise<LegalDisclaimerStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalDisclaimerStatus();
                return from_candid_LegalDisclaimerStatus_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalDisclaimerStatus();
            return from_candid_LegalDisclaimerStatus_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegalDisclaimerStatusFor(arg0: Principal): Promise<LegalDisclaimerStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalDisclaimerStatusFor(arg0);
                return from_candid_LegalDisclaimerStatus_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalDisclaimerStatusFor(arg0);
            return from_candid_LegalDisclaimerStatus_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLongevityScore(arg0: bigint): Promise<LongevityScore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLongevityScore(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLongevityScore(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoolBalances(): Promise<TokenDistribution> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoolBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoolBalances();
            return result;
        }
    }
    async getPreferences(): Promise<Preferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return from_candid_Preferences_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return from_candid_Preferences_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplementStoreSize(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplementStoreSize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplementStoreSize();
            return result;
        }
    }
    async getTokenBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenBalance();
            return result;
        }
    }
    async getTokenSupplyInfo(): Promise<TokenSupply> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenSupplyInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenSupplyInfo();
            return result;
        }
    }
    async getTokenTransactions(): Promise<Array<QueryTokenTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenTransactions();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenTransactions();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainings(): Promise<Array<Training>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainings();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainings();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async mintRewardTokens(arg0: Principal, arg1: TokenBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mintRewardTokens(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintRewardTokens(arg0, arg1);
            return result;
        }
    }
    async resetAllSupplements(): Promise<ResetResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllSupplements();
                return from_candid_ResetResponse_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllSupplements();
            return from_candid_ResetResponse_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAnalyses(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAnalyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAnalyses();
            return result;
        }
    }
    async resetLegalDisclaimerStatus(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetLegalDisclaimerStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetLegalDisclaimerStatus();
            return result;
        }
    }
    async resetTokenDistribution(): Promise<TokenDistribution> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTokenDistribution();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTokenDistribution();
            return result;
        }
    }
    async saveBodyComposition(arg0: number, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBodyComposition(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBodyComposition(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveTraining(arg0: Training): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTraining(to_candid_Training_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTraining(to_candid_Training_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setLegalDisclaimerSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLegalDisclaimerSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLegalDisclaimerSeen();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async sortSupplementsByTime(): Promise<SortResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.sortSupplementsByTime();
                return from_candid_SortResponse_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sortSupplementsByTime();
            return from_candid_SortResponse_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleSupplement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSupplement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSupplement(arg0);
            return result;
        }
    }
    async transferTokens(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferTokens(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferTokens(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unlockUtility(arg0: UtilityType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockUtility(to_candid_UtilityType_n77(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockUtility(to_candid_UtilityType_n77(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJournalEntry(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, arg1);
            return result;
        }
    }
    async updateSupplement(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplement(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplement(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_BMIIndicatorCategory_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BMIIndicatorCategory): BMIIndicatorCategory {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_BodyComposition_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyComposition): BodyComposition {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ColorIndicator_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorIndicator): ColorIndicator {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DayData_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayData): DayData {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DayRoutines_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayRoutines): DayRoutines {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_LegalDisclaimerStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LegalDisclaimerStatus): LegalDisclaimerStatus {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Preferences_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Preferences): Preferences {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_QueryTokenTransaction_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryTokenTransaction): QueryTokenTransaction {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_ResetResponse_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResetResponse): ResetResponse {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SortResponse_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SortResponse): SortResponse {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_StressMetrics_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StressMetrics): StressMetrics {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_SupplementEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplementEntry): SupplementEntry {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SupplementResponse_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplementResponse): SupplementResponse {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TokenType_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenType): TokenType {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingIntensity_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingIntensity): TrainingIntensity {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingType): TrainingType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Training_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Training): Training {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AutophagyScore]): AutophagyScore | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BodyComposition]): BodyComposition | null {
    return value.length === 0 ? null : from_candid_BodyComposition_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LongevityScore]): LongevityScore | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionTime: _Time;
    longevityScore: _LongevityScore;
    routines: _DayRoutines;
    autophagyScore: _AutophagyScore;
}): {
    completionTime: Time;
    longevityScore: LongevityScore;
    routines: DayRoutines;
    autophagyScore: AutophagyScore;
} {
    return {
        completionTime: value.completionTime,
        longevityScore: value.longevityScore,
        routines: from_candid_DayRoutines_n27(_uploadFile, _downloadFile, value.routines),
        autophagyScore: value.autophagyScore
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nutritionMetrics: _NutritionMetrics;
    bodyComposition: _BodyCompositionInput;
    stressMetrics: _StressMetrics;
    fastingSession: _FastingSession;
    sleepMetrics: _SleepMetrics;
    trainingSessions: Array<_Training>;
}): {
    nutritionMetrics: NutritionMetrics;
    bodyComposition: BodyCompositionInput;
    stressMetrics: StressMetrics;
    fastingSession: FastingSession;
    sleepMetrics: SleepMetrics;
    trainingSessions: Array<Training>;
} {
    return {
        nutritionMetrics: value.nutritionMetrics,
        bodyComposition: value.bodyComposition,
        stressMetrics: from_candid_StressMetrics_n29(_uploadFile, _downloadFile, value.stressMetrics),
        fastingSession: value.fastingSession,
        sleepMetrics: value.sleepMetrics,
        trainingSessions: from_candid_vec_n33(_uploadFile, _downloadFile, value.trainingSessions)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supplements: Array<_SupplementEntry>;
    message: string;
}): {
    supplements: Array<SupplementEntry>;
    message: string;
} {
    return {
        supplements: from_candid_vec_n4(_uploadFile, _downloadFile, value.supplements),
        message: value.message
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stressColorIndicator: _ColorIndicator;
    bloodPressureDiastolic: bigint;
    pulse: bigint;
    bloodPressureSystolic: bigint;
}): {
    stressColorIndicator: ColorIndicator;
    bloodPressureDiastolic: bigint;
    pulse: bigint;
    bloodPressureSystolic: bigint;
} {
    return {
        stressColorIndicator: from_candid_ColorIndicator_n31(_uploadFile, _downloadFile, value.stressColorIndicator),
        bloodPressureDiastolic: value.bloodPressureDiastolic,
        pulse: value.pulse,
        bloodPressureSystolic: value.bloodPressureSystolic
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    trainingType: _TrainingType;
    intensity: _TrainingIntensity;
}): {
    durationMins: bigint;
    trainingType: TrainingType;
    intensity: TrainingIntensity;
} {
    return {
        durationMins: value.durationMins,
        trainingType: from_candid_TrainingType_n36(_uploadFile, _downloadFile, value.trainingType),
        intensity: from_candid_TrainingIntensity_n38(_uploadFile, _downloadFile, value.intensity)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bmi: number;
    currentBodyFatPercentage: number;
    bmiCategory: _BMIIndicatorCategory;
    history: Array<_BodyCompentry>;
    currentMuscleMass: number;
    currentWeight: number;
}): {
    bmi: number;
    currentBodyFatPercentage: number;
    bmiCategory: BMIIndicatorCategory;
    history: Array<BodyCompentry>;
    currentMuscleMass: number;
    currentWeight: number;
} {
    return {
        bmi: value.bmi,
        currentBodyFatPercentage: value.currentBodyFatPercentage,
        bmiCategory: from_candid_BMIIndicatorCategory_n44(_uploadFile, _downloadFile, value.bmiCategory),
        history: value.history,
        currentMuscleMass: value.currentMuscleMass,
        currentWeight: value.currentWeight
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    birthYear: bigint;
    name: string;
    preferences: _Preferences;
    gender: _Gender;
    bodyHeightCm: bigint;
}): {
    birthYear: bigint;
    name: string;
    preferences: Preferences;
    gender: Gender;
    bodyHeightCm: bigint;
} {
    return {
        birthYear: value.birthYear,
        name: value.name,
        preferences: from_candid_Preferences_n49(_uploadFile, _downloadFile, value.preferences),
        gender: from_candid_Gender_n52(_uploadFile, _downloadFile, value.gender),
        bodyHeightCm: value.bodyHeightCm
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    language: {
        de: null;
    } | {
        en: null;
    };
}): {
    language: Variant_de_en;
} {
    return {
        language: from_candid_variant_n51(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastSeenTimestamp: [] | [_Time];
    hasSeenDisclaimer: boolean;
}): {
    lastSeenTimestamp?: Time;
    hasSeenDisclaimer: boolean;
} {
    return {
        lastSeenTimestamp: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.lastSeenTimestamp)),
        hasSeenDisclaimer: value.hasSeenDisclaimer
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    dosage: string;
    name: string;
    note: [] | [string];
    time: string;
    completed: boolean;
}): {
    id: bigint;
    dosage: string;
    name: string;
    note?: string;
    time: string;
    completed: boolean;
} {
    return {
        id: value.id,
        dosage: value.dosage,
        name: value.name,
        note: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.note)),
        time: value.time,
        completed: value.completed
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    timestamp: _Time;
    tokenType: _TokenType;
    amount: bigint;
    transactionId: bigint;
}): {
    description: string;
    timestamp: Time;
    tokenType: TokenType;
    amount: bigint;
    transactionId: bigint;
} {
    return {
        description: value.description,
        timestamp: value.timestamp,
        tokenType: from_candid_TokenType_n66(_uploadFile, _downloadFile, value.tokenType),
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_RoutineDayId, _DayData]): [RoutineDayId, DayData] {
    return [
        value[0],
        from_candid_DayData_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): ColorIndicator {
    return "red" in value ? ColorIndicator.red : "green" in value ? ColorIndicator.green : "yellow" in value ? ColorIndicator.yellow : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    yoga: null;
} | {
    strength: null;
} | {
    cardio: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "yoga";
    yoga: null;
} | {
    __kind__: "strength";
    strength: null;
} | {
    __kind__: "cardio";
    cardio: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "yoga" in value ? {
        __kind__: "yoga",
        yoga: value.yoga
    } : "strength" in value ? {
        __kind__: "strength",
        strength: value.strength
    } : "cardio" in value ? {
        __kind__: "cardio",
        cardio: value.cardio
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TrainingIntensity {
    return "low" in value ? TrainingIntensity.low : "high" in value ? TrainingIntensity.high : "medium" in value ? TrainingIntensity.medium : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    slightlyLow: null;
} | {
    tooHigh: null;
} | {
    tooLow: null;
} | {
    slightlyHigh: null;
} | {
    optimal: null;
}): BMIIndicatorCategory {
    return "slightlyLow" in value ? BMIIndicatorCategory.slightlyLow : "tooHigh" in value ? BMIIndicatorCategory.tooHigh : "tooLow" in value ? BMIIndicatorCategory.tooLow : "slightlyHigh" in value ? BMIIndicatorCategory.slightlyHigh : "optimal" in value ? BMIIndicatorCategory.optimal : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    de: null;
} | {
    en: null;
}): Variant_de_en {
    return "de" in value ? Variant_de_en.de : "en" in value ? Variant_de_en.en : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n62(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goal: null;
} | {
    routine: null;
} | {
    bonus: null;
}): TokenType {
    return "goal" in value ? TokenType.goal : "routine" in value ? TokenType.routine : "bonus" in value ? TokenType.bonus : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_RoutineDayId, _DayData]>): Array<[RoutineDayId, DayData]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Training>): Array<Training> {
    return value.map((x)=>from_candid_Training_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupplementEntry>): Array<SupplementEntry> {
    return value.map((x)=>from_candid_SupplementEntry_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueryTokenTransaction>): Array<QueryTokenTransaction> {
    return value.map((x)=>from_candid_QueryTokenTransaction_n64(_uploadFile, _downloadFile, x));
}
function to_candid_ColorIndicator_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorIndicator): _ColorIndicator {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DayRoutines_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayRoutines): _DayRoutines {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_Preferences_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Preferences): _Preferences {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_StressMetrics_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StressMetrics): _StressMetrics {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingIntensity_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingIntensity): _TrainingIntensity {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingType): _TrainingType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Training_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Training): _Training {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UtilityType_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UtilityType): _UtilityType {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nutritionMetrics: NutritionMetrics;
    bodyComposition: BodyCompositionInput;
    stressMetrics: StressMetrics;
    fastingSession: FastingSession;
    sleepMetrics: SleepMetrics;
    trainingSessions: Array<Training>;
}): {
    nutritionMetrics: _NutritionMetrics;
    bodyComposition: _BodyCompositionInput;
    stressMetrics: _StressMetrics;
    fastingSession: _FastingSession;
    sleepMetrics: _SleepMetrics;
    trainingSessions: Array<_Training>;
} {
    return {
        nutritionMetrics: value.nutritionMetrics,
        bodyComposition: value.bodyComposition,
        stressMetrics: to_candid_StressMetrics_n12(_uploadFile, _downloadFile, value.stressMetrics),
        fastingSession: value.fastingSession,
        sleepMetrics: value.sleepMetrics,
        trainingSessions: to_candid_vec_n16(_uploadFile, _downloadFile, value.trainingSessions)
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stressColorIndicator: ColorIndicator;
    bloodPressureDiastolic: bigint;
    pulse: bigint;
    bloodPressureSystolic: bigint;
}): {
    stressColorIndicator: _ColorIndicator;
    bloodPressureDiastolic: bigint;
    pulse: bigint;
    bloodPressureSystolic: bigint;
} {
    return {
        stressColorIndicator: to_candid_ColorIndicator_n14(_uploadFile, _downloadFile, value.stressColorIndicator),
        bloodPressureDiastolic: value.bloodPressureDiastolic,
        pulse: value.pulse,
        bloodPressureSystolic: value.bloodPressureSystolic
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    trainingType: TrainingType;
    intensity: TrainingIntensity;
}): {
    durationMins: bigint;
    trainingType: _TrainingType;
    intensity: _TrainingIntensity;
} {
    return {
        durationMins: value.durationMins,
        trainingType: to_candid_TrainingType_n19(_uploadFile, _downloadFile, value.trainingType),
        intensity: to_candid_TrainingIntensity_n21(_uploadFile, _downloadFile, value.intensity)
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    birthYear: bigint;
    name: string;
    preferences: Preferences;
    gender: Gender;
    bodyHeightCm: bigint;
}): {
    birthYear: bigint;
    name: string;
    preferences: _Preferences;
    gender: _Gender;
    bodyHeightCm: bigint;
} {
    return {
        birthYear: value.birthYear,
        name: value.name,
        preferences: to_candid_Preferences_n71(_uploadFile, _downloadFile, value.preferences),
        gender: to_candid_Gender_n74(_uploadFile, _downloadFile, value.gender),
        bodyHeightCm: value.bodyHeightCm
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    language: Variant_de_en;
}): {
    language: {
        de: null;
    } | {
        en: null;
    };
} {
    return {
        language: to_candid_variant_n73(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorIndicator): {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == ColorIndicator.red ? {
        red: null
    } : value == ColorIndicator.green ? {
        green: null
    } : value == ColorIndicator.yellow ? {
        yellow: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "yoga";
    yoga: null;
} | {
    __kind__: "strength";
    strength: null;
} | {
    __kind__: "cardio";
    cardio: null;
}): {
    other: string;
} | {
    yoga: null;
} | {
    strength: null;
} | {
    cardio: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "yoga" ? {
        yoga: value.yoga
    } : value.__kind__ === "strength" ? {
        strength: value.strength
    } : value.__kind__ === "cardio" ? {
        cardio: value.cardio
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingIntensity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TrainingIntensity.low ? {
        low: null
    } : value == TrainingIntensity.high ? {
        high: null
    } : value == TrainingIntensity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_de_en): {
    de: null;
} | {
    en: null;
} {
    return value == Variant_de_en.de ? {
        de: null
    } : value == Variant_de_en.en ? {
        en: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UtilityType): {
    advancedAnalytics: null;
} | {
    longevityCircleMembership: null;
} | {
    supplementPlans: null;
} {
    return value == UtilityType.advancedAnalytics ? {
        advancedAnalytics: null
    } : value == UtilityType.longevityCircleMembership ? {
        longevityCircleMembership: null
    } : value == UtilityType.supplementPlans ? {
        supplementPlans: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Training>): Array<_Training> {
    return value.map((x)=>to_candid_Training_n17(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
